#!/bin/sh   

#Address Book in Shell Script

create()
{
echo "Enter address book name"
read ab
#check address book is available or not in current working directory
res=`ls | grep $ab | wc -w`
if [ $res -gt 0 ]
then
echo "Error: File is already exixting"
else
touch $ab
echo "Address book created :)"
fi

}
display()
{
echo "Enter address book name"
read ab
#check address book is available or not in current working directory
res=`ls | grep $ab | wc -w`
if [ $res -gt 0 ]
then
cat $ab
else
echo "Error: File is not exixting"
fi

}
insert()
{
echo "Enter address book name"
read ab
#check address book is available or not in current working directory
res=`ls | grep $ab | wc -w`
if [ $res -gt 0 ]
then

echo "Enter Email"
read email
#check email is present in address book or not
len=`cat $ab | grep $email | wc -w`
if [ $len -gt 0 ]
then
echo "Error: Email already existing!"
else
echo "Enter First name, Last name, mobile number"
read fname lname mobile
record=`echo $fname $lname $email $mobile`
echo $record >> $ab
echo "Record Inserted:)"
fi

else
echo "Error: File is not exixting!"
fi

}
modify()
{
echo "Enter address book name"
read ab
#check address book is available or not in current working directory
res=`ls | grep $ab | wc -w`
if [ $res -gt 0 ]
then
echo "Enter Email"
read email
#check email is present in address book or not
len=`cat $ab | grep $email | wc -w`
if [ $len -gt 0 ]
then
echo "Enter Modified First name, Last name, mobile number"
read fname lname mobile
new=`echo $fname $lname $email $mobile`
old=`cat $ab | grep $email`
echo "Old Record: $old"
echo "New Record: $new"

sed -i s/"$old"/"$new"/g $ab
echo "Record Modified:)"
else
echo "Error: Email already existing!"

fi

else
echo "Error: File is not exixting!"
fi

}

delete()
{
echo "Enter address book name"
read ab
#check address book is available or not in current working directory
res=`ls | grep $ab | wc -w`
if [ $res -gt 0 ]
then
echo "Enter Email"
read email
#check email is present in address book or not
len=`cat $ab | grep $email | wc -w`
if [ $len -gt 0 ]
then
old=`cat $ab | grep $email`

sed -i s/"$old"//g $ab
sed -i /^$/d $ab
echo "Record Deleted:)"
else
echo "Error: Email already existing!"
fi

else
echo "Error: File is not exixting!"
fi

}

while [ true ]
do
echo "**************MENU*********************"
echo "1. Create"

echo "2. Display"
echo "3. Insert Record"
echo "4. Modify Record"
echo "5. Delete Record"
echo "7. Exit"
echo "Enter Choice"
read choice
case $choice in
1) create ;;
2) display ;;
3) insert ;;
4) modify ;;
5) delete ;;
7) exit ;;
*) echo "Wrong Choice" ;;
esac
done
